<?php

/*
 * ScoutMagic — Copyright (C) 2026 Xavier Dubois and contributors
 * Licensed under AGPL-3.0-or-later. See LICENSE and NOTICE.
 */

declare(strict_types=1);

namespace Tests\Security;

use PHPUnit\Framework\TestCase;

/**
 * What the site says about the portable archive's password, checked against
 * what it does with it.
 *
 * Since issue #619 (IT-03) the password is generated by the site and KEPT,
 * in clear inside the encrypted `secrets.enc`, so that it can be revealed
 * at download and used to restore the archive here. That is a weaker
 * guarantee than « never stored in cleartext », which is what the screen,
 * the help topic and `SECURITY.md` used to say — and a security document
 * that describes a stronger guarantee than the code provides is the thing
 * an operator reads before deciding where to put an archive containing the
 * site's master key.
 *
 * **This class exists because those three places drifted apart once
 * already.** So the guard is keyed on what the code DOES. Stop keeping the
 * password and the first test fails, which is the signal to revisit the
 * prose. Drop the prose while the code still keeps it and the rest fail.
 * Neither half can move alone.
 */
final class PortablePassphraseDisclosureTest extends TestCase
{
    private static function root(): string
    {
        return dirname(__DIR__, 2);
    }

    /**
     * Source with comments and docblocks removed.
     *
     * Every textual assertion below runs on stripped source, because a
     * comment that mentions `encrypted_password` would otherwise satisfy a
     * test about code that stores it — and a docblock describing a
     * behaviour is the exact thing this class refuses to accept as
     * evidence.
     */
    private static function strippedSource(string $relativePath): string
    {
        $source = file_get_contents(self::root() . '/' . $relativePath);
        self::assertIsString($source, $relativePath . ' is unreadable.');

        $code = '';
        foreach (token_get_all($source) as $token) {
            if (is_array($token) && in_array($token[0], [T_COMMENT, T_DOC_COMMENT], true)) {
                continue;
            }
            $code .= is_array($token) ? $token[1] : $token;
        }

        return $code;
    }

    /**
     * The premise: the password is kept by the site, in secrets.enc, and
     * no longer travels in the backup task's payload.
     */
    public function testTheSiteKeepsTheGeneratedPasswordAndTheTaskCarriesNone(): void
    {
        $controller = self::strippedSource('core/Http/Controller/MaintenanceController.php');
        $this->assertStringContainsString('BackupPasswords', $controller, 'MaintenanceController no longer keeps the archive password.');

        $handler = self::strippedSource('core/Maintenance/Task/CreateBackupHandler.php');
        $this->assertStringContainsString('passwordFor(', $handler, 'CreateBackupHandler no longer reads the kept password.');

        $store = self::strippedSource('core/Maintenance/BackupPasswords.php');
        $this->assertStringContainsString("'backup_password_%d'", $store);
        $this->assertStringContainsString('->updateSecrets(', $store, 'BackupPasswords no longer writes into secrets.enc.');
    }

    /**
     * `SECURITY.md` must not promise more than the code delivers.
     *
     * The phrase this looks for is the one that was actually there, and the
     * one a future edit is most likely to reach for again.
     */
    public function testSecurityMdDoesNotClaimThePassphraseIsStoredNowhere(): void
    {
        $security = file_get_contents(self::root() . '/SECURITY.md');
        $this->assertIsString($security, 'SECURITY.md is unreadable.');

        $this->assertStringNotContainsString(
            'stored nowhere. An archive whose passphrase is lost',
            $security,
            'SECURITY.md claims the portable passphrase is stored nowhere, while MaintenanceController writes '
            . 'an encrypted copy into the backup task payload.'
        );
        $this->assertStringNotContainsString(
            'the screen says the phrase is stored nowhere',
            $security,
            'SECURITY.md asserts the Maintenance screen makes a claim it no longer makes.'
        );
    }

    /**
     * And it must state the caveat, not merely avoid the false sentence.
     *
     * Dropping the wrong claim and saying nothing in its place would pass a
     * test that only forbade the old words, and would leave the operator no
     * better informed than the lie did.
     */
    public function testSecurityMdStatesWhereThePasswordLivesAndWhoCanReadIt(): void
    {
        $security = file_get_contents(self::root() . '/SECURITY.md');
        $this->assertIsString($security, 'SECURITY.md is unreadable.');

        foreach (['kept in `secrets.enc`', 'backup_password_{id}', 'revealed on demand', 'journaled at `security` level'] as $needle) {
            $this->assertStringContainsString(
                $needle,
                $security,
                'SECURITY.md no longer says where the archive password lives (missing: ' . $needle . ').'
            );
        }
        $this->assertStringNotContainsString(
            'never stored in cleartext',
            $security,
            'SECURITY.md claims the archive password is never stored in cleartext, while secrets.enc keeps it.'
        );
    }

    /**
     * The screen and the help topic, which are what an operator actually
     * reads, must carry the same caveat in French.
     *
     * These two were corrected first; the assertion is here so that the
     * next correction cannot fix one document and forget the other, which
     * is precisely how this drift started.
     */
    public function testTheScreenAndTheHelpTopicBothCarryTheCaveat(): void
    {
        foreach ([
            'core/View/templates/config/maintenance/sauvegarde_manuelle.html.twig',
            'docs/help/sauvegarde-portable.md',
        ] as $path) {
            $contents = file_get_contents(self::root() . '/' . $path);
            $this->assertIsString($contents, $path . ' is unreadable.');
            $this->assertStringNotContainsString(
                'jamais enregistrée en clair',
                $contents,
                $path . ' still promises the password is never kept in cleartext.'
            );
            // What replaces it: the password is shown, and must be noted
            // because the server able to repeat it may be gone.
            $this->assertStringContainsString(
                "le redire n'existera peut-être plus",
                (string) preg_replace('/\s+/', ' ', $contents),
                $path . ' no longer tells the operator to note the password.'
            );
        }
    }
}
