<?php

declare(strict_types=1);

namespace Core\File;

use Smalot\PdfParser\Parser;

/**
 * Extracts a PDF's embedded text layer, when it has one. Most PDF
 * receipts/invoices (emailed, generated by accounting software, subsidy
 * documents) do — reading that text directly is exact (no hallucination
 * risk at all) and provider-agnostic (plain text works with any LLM,
 * unlike an image/document attachment, which not every provider's API
 * actually supports — see Modules\Finance\Task\
 * ExtractReceiptDataHandler). A scanned or photographed receipt saved as
 * PDF typically has no text layer; callers must fall back to
 * PdfRasterizer + image-based OCR for those.
 */
class PdfTextExtractor
{
    private const MIN_MEANINGFUL_CHARS = 20;

    /**
     * @return string|null the extracted text, or null when the PDF is
     *                      malformed or has no meaningful text layer
     */
    public function extractText(string $pdfContent): ?string
    {
        try {
            $text = trim((new Parser())->parseContent($pdfContent)->getText());
        } catch (\Throwable) {
            return null;
        }

        $meaningfulLength = mb_strlen(preg_replace('/\s+/', '', $text) ?? '');

        return $meaningfulLength >= self::MIN_MEANINGFUL_CHARS ? $text : null;
    }
}
