<?php
/**
 * ScoutMagic — Copyright (C) 2026 Xavier Dubois and contributors
 * Licensed under AGPL-3.0-or-later. See LICENSE and NOTICE.
 */

declare(strict_types=1);

namespace Modules\InboundMail\Mime;

use Modules\InboundMail\Client\FetchedAttachment;
use Modules\InboundMail\Client\FetchedMessage;

/**
 * A raw RFC 5322 message into a `FetchedMessage`.
 *
 * **Everything here is defensive**, because every byte of the input was
 * written by whoever knew the unit's address (§7.9). A malformed header, a
 * missing boundary, a body that claims an encoding it does not use — none
 * of them may throw, because a message that cannot be parsed must be
 * skipped, not allowed to stop the whole synchronisation and leave the
 * mailbox permanently stuck behind it.
 *
 * The rules that matter, and why:
 *
 * - **`multipart/alternative` prefers the HTML part but keeps the text**
 *   (§7.5). Keeping only one is what makes a message unsearchable later or
 *   unreadable now, and they are not interchangeable: the text part is what
 *   a consumer scans for a reference, the HTML part what a manager reads.
 * - **Headers are RFC 2047-decoded** — `=?UTF-8?Q?R=C3=A9servation?=` is a
 *   subject a Belgian unit gets every day, and a reference hidden inside an
 *   encoded word is invisible to a consumer that never decodes it.
 * - **Filenames come from RFC 2231 `filename*` when present**, falling back
 *   to a plain `filename`. Both are still untrusted: the stored name is
 *   generated by `UploadHandler`, and this one is only ever a label.
 */
class MimeMessageParser
{
    /**
     * How deep a nested multipart structure is followed. Real mail nests
     * two or three levels (`mixed` → `alternative` → `related`); anything
     * far beyond that is either broken or an attempt to make the parser
     * work forever on one message.
     */
    private const MAX_DEPTH = 8;

    public function __construct(private BulkMailDetector $bulkDetector = new BulkMailDetector())
    {
    }

    public function parse(string $raw, int $uid, string $folder): FetchedMessage
    {
        [$headerBlock, $body] = self::splitHeadersAndBody($raw);
        $headers = self::parseHeaders($headerBlock);

        $bodyText = '';
        $bodyHtml = '';
        $attachments = [];
        $this->walkPart($headers, $body, 0, $bodyText, $bodyHtml, $attachments);

        [$fromEmail, $fromName] = self::parseAddress(self::header($headers, 'from'));

        return new FetchedMessage(
            uid: $uid,
            folder: $folder,
            messageId: self::normaliseMessageId(self::header($headers, 'message-id')),
            subject: self::decodeWords(self::header($headers, 'subject')),
            fromEmail: $fromEmail,
            fromName: $fromName,
            toEmails: self::parseAddressList(self::header($headers, 'to')),
            inReplyTo: self::nullIfEmpty(self::normaliseMessageId(self::header($headers, 'in-reply-to'))),
            references: self::parseReferences(self::header($headers, 'references')),
            sentAt: self::parseDate(self::header($headers, 'date')),
            bodyText: $bodyText,
            bodyHtml: $bodyHtml,
            attachments: $attachments,
            isBulk: $this->bulkDetector->detect($headers, $fromEmail)
        );
    }

    // ── Structure ───────────────────────────────────────────────────────

    /**
     * @param array<string, string> $headers
     * @param FetchedAttachment[] $attachments
     */
    private function walkPart(
        array $headers,
        string $body,
        int $depth,
        string &$bodyText,
        string &$bodyHtml,
        array &$attachments
    ): void {
        if ($depth > self::MAX_DEPTH) {
            return;
        }

        $contentType = strtolower(self::header($headers, 'content-type'));
        $disposition = strtolower(self::parameterlessValue(self::header($headers, 'content-disposition')));

        if (str_starts_with($contentType, 'multipart/')) {
            $boundary = self::parameter(self::header($headers, 'content-type'), 'boundary');
            if ($boundary === null || $boundary === '') {
                // A multipart with no usable boundary: treat what is there
                // as text rather than losing the message entirely.
                self::appendBody($bodyText, self::decodeBody($headers, $body));
                return;
            }

            foreach (self::splitOnBoundary($body, $boundary) as $rawPart) {
                [$partHeaderBlock, $partBody] = self::splitHeadersAndBody($rawPart);
                $this->walkPart(
                    self::parseHeaders($partHeaderBlock),
                    $partBody,
                    $depth + 1,
                    $bodyText,
                    $bodyHtml,
                    $attachments
                );
            }

            return;
        }

        $filename = self::attachmentFilename($headers);

        // An `inline` part with no filename is body content — a `related`
        // message's HTML arrives exactly that way. An `attachment` is an
        // attachment whether or not it has a name.
        if ($disposition === 'attachment' || $filename !== null) {
            $attachments[] = new FetchedAttachment(
                filename: $filename ?? 'piece-jointe',
                declaredMimeType: self::parameterlessValue(self::header($headers, 'content-type')) ?: 'application/octet-stream',
                bytes: self::decodeBody($headers, $body),
                isInline: $disposition === 'inline',
                contentId: self::nullIfEmpty(trim(self::header($headers, 'content-id'), '<> ')) 
            );

            return;
        }

        $decoded = self::decodeBody($headers, $body);

        if (str_starts_with($contentType, 'text/html')) {
            self::appendBody($bodyHtml, $decoded);
            return;
        }

        // text/plain, and anything unlabelled: RFC 2045 says a part with no
        // Content-Type is text/plain, and treating an unknown one as text
        // keeps a badly-built message readable.
        self::appendBody($bodyText, $decoded);
    }

    private static function appendBody(string &$target, string $addition): void
    {
        if (trim($addition) === '') {
            return;
        }

        $target = $target === '' ? $addition : $target . "\n\n" . $addition;
    }

    /**
     * @return list<string>
     */
    private static function splitOnBoundary(string $body, string $boundary): array
    {
        $delimiter = '--' . $boundary;
        $parts = [];
        $current = null;

        foreach (preg_split('/\r\n|\n|\r/', $body) ?: [] as $line) {
            if ($line === $delimiter || $line === $delimiter . '--') {
                if ($current !== null) {
                    $parts[] = implode("\r\n", $current);
                }
                $current = $line === $delimiter . '--' ? null : [];
                continue;
            }

            if ($current !== null) {
                $current[] = $line;
            }
        }

        if ($current !== null && $current !== []) {
            $parts[] = implode("\r\n", $current);
        }

        return $parts;
    }

    // ── Headers ─────────────────────────────────────────────────────────

    /**
     * @return array{0: string, 1: string}
     */
    private static function splitHeadersAndBody(string $raw): array
    {
        $raw = str_replace(["\r\n", "\r"], "\n", $raw);
        $separator = strpos($raw, "\n\n");

        if ($separator === false) {
            return [$raw, ''];
        }

        return [substr($raw, 0, $separator), substr($raw, $separator + 2)];
    }

    /**
     * Header names lowercased, continuation lines unfolded. A repeated
     * header keeps the first occurrence, which is what every reader does
     * for the ones this class cares about.
     *
     * @return array<string, string>
     */
    private static function parseHeaders(string $block): array
    {
        $headers = [];
        $name = null;

        foreach (explode("\n", $block) as $line) {
            if ($line !== '' && ($line[0] === ' ' || $line[0] === "\t")) {
                if ($name !== null) {
                    $headers[$name] .= ' ' . trim($line);
                }
                continue;
            }

            $colon = strpos($line, ':');
            if ($colon === false) {
                $name = null;
                continue;
            }

            $candidate = strtolower(trim(substr($line, 0, $colon)));
            if (isset($headers[$candidate])) {
                $name = null;
                continue;
            }

            $name = $candidate;
            $headers[$name] = trim(substr($line, $colon + 1));
        }

        return $headers;
    }

    /**
     * @param array<string, string> $headers
     */
    private static function header(array $headers, string $name): string
    {
        return $headers[$name] ?? '';
    }

    private static function parameterlessValue(string $headerValue): string
    {
        $semicolon = strpos($headerValue, ';');

        return trim($semicolon === false ? $headerValue : substr($headerValue, 0, $semicolon));
    }

    private static function parameter(string $headerValue, string $parameter): ?string
    {
        if (preg_match('/;\s*' . preg_quote($parameter, '/') . '\s*=\s*"([^"]*)"/i', $headerValue, $m) === 1) {
            return $m[1];
        }
        if (preg_match('/;\s*' . preg_quote($parameter, '/') . '\s*=\s*([^;\s]+)/i', $headerValue, $m) === 1) {
            return trim($m[1], '"');
        }

        return null;
    }

    /**
     * @param array<string, string> $headers
     */
    private static function attachmentFilename(array $headers): ?string
    {
        $disposition = self::header($headers, 'content-disposition');
        $contentType = self::header($headers, 'content-type');

        // RFC 2231 first: `filename*=UTF-8''Rapport%20final.pdf` is how a
        // non-ASCII name actually travels, and reading only `filename`
        // yields the ASCII-mangled fallback the sender left for old
        // clients.
        foreach ([$disposition, $contentType] as $source) {
            $extended = self::parameter($source, 'filename*') ?? self::parameter($source, 'name*');
            if ($extended !== null && $extended !== '') {
                return self::decodeExtendedParameter($extended);
            }
        }

        foreach ([$disposition, $contentType] as $source) {
            $plain = self::parameter($source, 'filename') ?? self::parameter($source, 'name');
            if ($plain !== null && $plain !== '') {
                return self::decodeWords($plain);
            }
        }

        return null;
    }

    /**
     * RFC 2231: `charset'language'percent-encoded`.
     */
    private static function decodeExtendedParameter(string $value): string
    {
        $parts = explode("'", $value, 3);
        if (count($parts) < 3) {
            return rawurldecode($value);
        }

        $decoded = rawurldecode($parts[2]);

        return self::toUtf8($decoded, $parts[0] !== '' ? $parts[0] : 'UTF-8');
    }

    /**
     * RFC 2047 encoded words, which is how any accented subject arrives.
     */
    public static function decodeWords(string $value): string
    {
        if (!str_contains($value, '=?')) {
            return $value;
        }

        // Whitespace BETWEEN two adjacent encoded words is not content —
        // RFC 2047 §6.2 — so it is removed first. Doing it afterwards
        // cannot work: by then the `?=` and `=?` markers that identify the
        // join are gone, and a name split across two words keeps a space in
        // the middle.
        $value = preg_replace('/\?=\s+=\?/', '?==?', $value) ?? $value;

        $decoded = preg_replace_callback(
            '/=\?([^?]+)\?([BbQq])\?([^?]*)\?=/',
            static function (array $m): string {
                $charset = $m[1];
                $text = strtoupper($m[2]) === 'B'
                    ? (base64_decode($m[3], true) ?: '')
                    : quoted_printable_decode(str_replace('_', ' ', $m[3]));

                return self::toUtf8($text, $charset);
            },
            $value
        );

        return $decoded ?? $value;
    }

    private static function toUtf8(string $value, string $charset): string
    {
        $charset = strtoupper(trim($charset));
        if ($charset === '' || $charset === 'UTF-8' || $charset === 'US-ASCII') {
            return $value;
        }

        $converted = @mb_convert_encoding($value, 'UTF-8', $charset);

        return is_string($converted) && $converted !== '' ? $converted : $value;
    }

    /**
     * @param array<string, string> $headers
     */
    private static function decodeBody(array $headers, string $body): string
    {
        $encoding = strtolower(trim(self::header($headers, 'content-transfer-encoding')));

        $decoded = match ($encoding) {
            'base64' => base64_decode($body, false) ?: '',
            'quoted-printable' => quoted_printable_decode($body),
            default => $body,
        };

        $charset = self::parameter(self::header($headers, 'content-type'), 'charset');

        return rtrim(self::toUtf8($decoded, $charset ?? 'UTF-8'), "\r\n");
    }

    // ── Addresses, ids and dates ────────────────────────────────────────

    /**
     * @return array{0: string, 1: ?string}
     */
    private static function parseAddress(string $value): array
    {
        $value = self::decodeWords(trim($value));

        if (preg_match('/^(.*?)<([^>]+)>\s*$/', $value, $m) === 1) {
            $name = trim($m[1], " \t\"");

            return [strtolower(trim($m[2])), $name === '' ? null : $name];
        }

        return [strtolower(trim($value)), null];
    }

    /**
     * @return string[]
     */
    private static function parseAddressList(string $value): array
    {
        if (trim($value) === '') {
            return [];
        }

        $emails = [];
        foreach (explode(',', $value) as $entry) {
            [$email] = self::parseAddress($entry);
            if ($email !== '') {
                $emails[] = $email;
            }
        }

        return array_values(array_unique($emails));
    }

    /**
     * @return string[]
     */
    private static function parseReferences(string $value): array
    {
        if (preg_match_all('/<([^>]+)>/', $value, $m) === 0) {
            return [];
        }

        return array_values(array_unique(array_map(static fn(string $id) => trim($id), $m[1])));
    }

    /**
     * Angle brackets stripped, so two headers naming the same message
     * compare equal whether or not the sender wrote them.
     */
    private static function normaliseMessageId(string $value): string
    {
        return trim($value, "<> \t");
    }

    /**
     * An RFC 2822 `Date:` header — "Mon, 12 Jul 2027 09:30:00 +0200",
     * not a stored ISO timestamp. Deliberately NOT
     * DateInput::fromStorage(), which requires the value to OPEN with a
     * calendar date and would refuse every well-formed mail header there
     * is (SECURITY.md § 35). The two edges that reading has are both
     * already closed here: the blank is guarded above, and a malformed
     * value falls through instead of throwing.
     */
    private static function parseDate(string $value): \DateTimeImmutable
    {
        $value = trim($value);
        if ($value !== '') {
            try {
                return new \DateTimeImmutable($value);
            } catch (\Exception) {
                // Falls through: a malformed Date: must not lose the mail.
            }
        }

        return new \DateTimeImmutable('now');
    }

    private static function nullIfEmpty(string $value): ?string
    {
        return $value === '' ? null : $value;
    }
}
