<?php

/*
 * ScoutMagic — Copyright (C) 2026 Xavier Dubois and contributors
 * Licensed under AGPL-3.0-or-later. See LICENSE and NOTICE.
 */

declare(strict_types=1);

namespace Tests\Core\View;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * What the site tells a family about the copies of their data that now
 * live at Google.
 *
 * IT-08 connected a destination; IT-09 made it **receive an archive every
 * day and keep it**. That turns a possibility into a processing
 * operation: Google holds a full copy of the site's database — every
 * member's name, address and photograph, encrypted — indefinitely, on
 * infrastructure that may not be in the European Economic Area. AGENTS.md
 * requires a new external integration to reach two places, and this test
 * is about both: the default privacy notice
 * (`Core\View\RgpdContentService::getDefaultContent()`, whose body is
 * `core/View/rgpd_default.html`) and the prompt that regenerates a
 * tailored one (`buildSystemPrompt()`, rule 28).
 *
 * **Deliberately about the words.** A promise a family reads is not
 * enforced by a unit test of a service; it is enforced by the sentence
 * being there and being true. What is mechanical — and what this catches
 * — is the sentence that got deleted in a refactor, or the one IT-08 left
 * behind that IT-09 made false.
 */
final class RemoteBackupRgpdCoverageTest extends TestCase
{
    private const NOTICE = 'core/View/rgpd_default.html';
    private const PROMPT = 'core/View/RgpdContentService.php';

    private static function read(string $path): string
    {
        return (string) file_get_contents(dirname(__DIR__, 3) . '/' . $path);
    }

    /**
     * The four facts IT-09 introduces, each in both documents.
     *
     * @return array<string, array{list<string>}>
     */
    public static function factProvider(): array
    {
        return [
            'the send is automatic and recurring' => [['vingt-quatre heures']],
            'the archive stays there rather than passing through' => [['durablement']],
            'Google is a processor for it' => [['article 28']],
            'the data may leave the EEA' => [['Espace économique européen']],
        ];
    }

    /**
     * @param list<string> $needles
     */
    #[DataProvider('factProvider')]
    public function testBothDocumentsCarryTheFact(array $needles): void
    {
        foreach ([self::NOTICE, self::PROMPT] as $path) {
            $content = self::read($path);
            foreach ($needles as $needle) {
                // Case-insensitively: the prompt shouts some of these at
                // the model in capitals, and which half is emphasised is
                // not the fact being pinned.
                $this->assertStringContainsStringIgnoringCase(
                    $needle,
                    $content,
                    $path . ' no longer says this about the off-site backup, and a family reading it would be '
                    . 'told less than what actually happens to their data.'
                );
            }
        }
    }

    /**
     * **The claim IT-08 made that IT-09 retires.** The phrase was the
     * unit's to choose and to keep; it is now generated by the site and
     * stored on the server. A notice still saying « choisie par l'unité »
     * would be telling a family that a human holds the only key, which is
     * exactly the thing that stopped being true.
     */
    public function testTheRetiredClaimAboutAChosenPassphraseIsGone(): void
    {
        foreach ([self::NOTICE, self::PROMPT] as $path) {
            $content = self::read($path);
            $this->assertStringNotContainsString('phrase de passe choisie par l\'unité', $content, $path);
            $this->assertStringNotContainsString('phrase de passe que l\'unité seule connaît', $content, $path);
        }
    }

    /**
     * And the guarantee that still holds is still stated: what Google
     * receives is already encrypted, so it holds a file and not a key.
     * Losing this sentence would be losing the one reassurance the rest
     * of the paragraph earns.
     */
    public function testTheNoticeStillSaysGoogleHoldsCiphertextAndNoKey(): void
    {
        $notice = self::read(self::NOTICE);

        $this->assertStringContainsString('chiffrée avant de quitter le serveur', $notice);
        $this->assertStringContainsString('Google compris', $notice);
    }
}
