<?php
/**
 * ScoutMagic — Copyright (C) 2026 Xavier Dubois and contributors
 * Licensed under AGPL-3.0-or-later. See LICENSE and NOTICE.
 */

declare(strict_types=1);

namespace Core\Maintenance;

use Core\Maintenance\Remote\RemotePassphrase;
use Core\Security\SecretManager;

/**
 * The password each downloadable archive is encrypted with — generated by
 * the site, one per archive, kept in `storage/config/secrets.enc` under
 * `backup_password_{id}` (issue #619, docs/chantiers/CHANTIER-maintenance.md
 * IT-03).
 *
 * **Nobody types a backup password any more.** The site generates it when
 * the archive is requested, uses it when the archive is written, reveals it
 * when somebody is about to download the file, and finds it again when that
 * archive is restored on this server. It used to be typed into the form
 * and carried, encrypted, in the scheduled task's payload — and then
 * forgotten: the site could not restore its own archive without asking for
 * a password it had never kept.
 *
 * **One per archive**, so that revealing the password of one download says
 * nothing about any other. The alphabet is RemotePassphrase's, without
 * `I`, `L`, `O`, `0` or `1`, in six groups of five, because it is made to
 * be copied onto paper — 30 characters out of 31, about 148 bits.
 *
 * **Deleting an archive deletes its password** (BackupRetention::forget()),
 * or the secrets file would grow by one entry per backup, forever.
 *
 * Every change goes through SecretManager::updateSecrets(), under a lock:
 * a web request issues a password while a cron purge forgets another, and
 * two unlocked read-then-write passes would keep only one of the two.
 */
final class BackupPasswords
{
    private const KEY_TEMPLATE = 'backup_password_%d';

    /**
     * The password of the safety copy a full reset takes (IT-03b). Not
     * keyed by a row: the reset empties the `backups` table and deletes
     * secrets.enc itself, so this password is revealed on the reset page,
     * and must be noted, before anything is erased.
     */
    public const FULL_RESET_KEY = 'full_reset_password';

    public function __construct(private readonly SecretManager $secrets)
    {
    }

    /** The store of an installation, from its storage directory. */
    public static function forStorage(string $storagePath): self
    {
        return new self(new SecretManager($storagePath . '/keys/master.key', $storagePath . '/config/secrets.enc'));
    }

    public static function keyFor(int $backupId): string
    {
        return sprintf(self::KEY_TEMPLATE, $backupId);
    }

    /**
     * A new password, not yet kept — for an archive written before its
     * `backups` row exists (the safety copies, IT-03b), kept with store()
     * as soon as the row has an id.
     */
    public static function generate(): string
    {
        return RemotePassphrase::generate();
    }

    /**
     * The password for a safety copy, or null where it cannot be both used
     * and kept — a host whose libzip cannot encrypt, or an installation
     * with no secrets file to keep it in: the operation still gets its
     * safety net, in clear, rather than being refused one or given one
     * nobody could open.
     */
    public function forSafetyCopy(BackupServiceInterface $backupService): ?string
    {
        return $this->secrets->isInitialized() && $backupService->supportsZipEncryption()
            ? self::generate()
            : null;
    }

    /**
     * Keeps the password of a safety copy under its row, when it has one.
     * A failure here fails the operation: an archive whose password was
     * not kept is an archive nobody can restore.
     */
    public function keepFor(int $backupId, ?string $password): void
    {
        if ($password !== null) {
            $this->store($backupId, $password);
        }
    }

    /**
     * Generates the password of a new archive and keeps it.
     *
     * @throws \RuntimeException when the secrets file cannot be written —
     *         the archive must not be created with a password nobody kept
     */
    public function issue(int $backupId): string
    {
        $password = self::generate();
        $this->store($backupId, $password);

        return $password;
    }

    /**
     * Keeps a password the site did not generate: an archive requested
     * before this change, whose typed password was still in its task.
     */
    public function store(int $backupId, string $password): void
    {
        $this->secrets->updateSecrets(static function (array $secrets) use ($backupId, $password): array {
            $secrets[self::keyFor($backupId)] = $password;

            return $secrets;
        });
    }

    /** Null when the archive has none kept: older, unencrypted, or already forgotten. */
    public function passwordFor(int $backupId): ?string
    {
        if (!$this->secrets->isInitialized()) {
            return null;
        }

        $value = $this->secrets->readSecrets()[self::keyFor($backupId)] ?? null;

        return is_string($value) && $value !== '' ? $value : null;
    }

    /**
     * The password the next full reset will encrypt its safety copy with,
     * generated the first time it is asked for and the same afterwards —
     * revealing it twice must not show two different passwords, one of
     * which would open nothing.
     */
    public function fullResetPassword(): string
    {
        $kept = $this->secrets->readSecrets()[self::FULL_RESET_KEY] ?? null;
        if (is_string($kept) && $kept !== '') {
            return $kept;
        }

        // Checked again under the lock: two reveals racing each other must
        // still end up showing the same password.
        $password = '';
        $this->secrets->updateSecrets(static function (array $secrets) use (&$password): array {
            $current = $secrets[self::FULL_RESET_KEY] ?? null;
            $password = is_string($current) && $current !== '' ? $current : self::generate();
            $secrets[self::FULL_RESET_KEY] = $password;

            return $secrets;
        });

        return $password;
    }

    /** The full reset's password if it was revealed, null otherwise. */
    public function revealedFullResetPassword(): ?string
    {
        if (!$this->secrets->isInitialized()) {
            return null;
        }
        $kept = $this->secrets->readSecrets()[self::FULL_RESET_KEY] ?? null;

        return is_string($kept) && $kept !== '' ? $kept : null;
    }

    /**
     * The archives that have a password kept, read in one pass — the
     * recent-backups list asks for all its rows at once.
     *
     * @return list<int>
     */
    public function keptIds(): array
    {
        if (!$this->secrets->isInitialized()) {
            return [];
        }

        $ids = [];
        foreach (array_keys($this->secrets->readSecrets()) as $key) {
            if (preg_match('/^backup_password_(\d+)$/', (string) $key, $match) === 1) {
                $ids[] = (int) $match[1];
            }
        }

        return $ids;
    }

    /**
     * Drops the password of a deleted archive. Silent when there is none
     * to drop — most archives types never had one.
     */
    public function forget(int $backupId): void
    {
        if (!$this->secrets->isInitialized()) {
            return;
        }

        $key = self::keyFor($backupId);
        if (!array_key_exists($key, $this->secrets->readSecrets())) {
            return;
        }

        $this->secrets->updateSecrets(static function (array $secrets) use ($key): array {
            unset($secrets[$key]);

            return $secrets;
        });
    }
}
