<?php
/**
 * ScoutMagic — Copyright (C) 2026 Xavier Dubois and contributors
 * Licensed under AGPL-3.0-or-later. See LICENSE and NOTICE.
 */

declare(strict_types=1);

namespace Core\Alert\Check;

use Core\Alert\AlertReading;
use Core\Alert\OperationalCheck;
use Core\Maintenance\Remote\RemoteBackupDestination;
use Core\Maintenance\Remote\RemotePassphrase;

/**
 * Is the only key that opens the off-site archives anywhere but on the
 * server those archives exist to outlive?
 *
 * **{@see RemoteBackupAgeCheck} and this one fail in opposite
 * directions.** That one catches a site whose archives never leave; this
 * one catches a site whose archives leave perfectly, every night, for a
 * year — and are all unreadable on the day they are needed, because the
 * phrase that decrypts them was generated by the site, stored in
 * `secrets.enc`, and never written down anywhere else. Nothing about that
 * site looks wrong until the server is gone, at which point nothing can
 * be done about it.
 *
 * **A binary check, so its two thresholds are one fact read both ways.**
 * The hysteresis the numeric checks need exists to stop a wobbling
 * measurement notifying in a loop; a statement somebody made does not
 * wobble.
 *
 * **Reading the phrase is not noting it**, so this is not derived from
 * the reveal journal. An administrator who opened the screen to check
 * something has seen it and copied nothing. Only a person can state that
 * a copy exists off this server, and {@see RemotePassphrase::markNoted()}
 * records the statement against the generation it was made for — so a
 * regeneration brings the alert back on its own, which is right: the new
 * phrase is a new thing to write down, and the old note now opens
 * nothing.
 *
 * **Two situations are not measured at all**, and both come back re-armed
 * rather than inconclusive, so that arriving in either CLEARS a triggered
 * alert instead of freezing it:
 *
 * - no destination chosen — nothing leaves the server, so there is no
 *   archive anywhere for a phrase to open. A unit that has not set up
 *   off-site sending is not failing at anything, and an alert every
 *   installation carries from its first day is one nobody reads;
 * - no phrase generated yet. The phrase is created by the first send
 *   ({@see RemotePassphrase::current()}), never at connection time, so a
 *   generation of 0 means nothing has yet been encrypted with anything.
 *   That is also what keeps this check off a site that connected a
 *   destination this afternoon and has not reached four in the morning.
 */
final class RemotePassphraseNotedCheck implements OperationalCheck
{
    public const KEY = 'remote_backup_passphrase_unnoted';

    public function __construct(
        private readonly RemoteBackupDestination $destination,
        private readonly RemotePassphrase $passphrase
    ) {
    }

    public function key(): string
    {
        return self::KEY;
    }

    public function label(): string
    {
        return 'Phrase de passe hors site';
    }

    public function read(): AlertReading
    {
        if (!$this->destination->isConfigured()) {
            return $this->notMeasured('aucune destination');
        }

        $generation = $this->passphrase->generation();
        if ($generation === 0) {
            return $this->notMeasured('aucune phrase');
        }

        $noted = $this->passphrase->isNoted();

        return new AlertReading(
            overTrigger: !$noted,
            underRearm: $noted,
            value: $noted ? 'notée' : 'génération ' . $generation . ' non notée',
            title: 'Personne n\'a noté la phrase de passe des sauvegardes distantes.',
            why: 'Les archives envoyées hors site sont chiffrées avec une phrase que le site a générée '
                . 'et qu\'il garde sur ce serveur — celui-là même auquel elles doivent survivre. Tant '
                . 'qu\'elle n\'existe nulle part ailleurs, ces archives ne s\'ouvriront pas le jour où '
                . 'l\'hébergement disparaît. Affichez-la, recopiez-la hors du site, puis confirmez-le.',
            actionUrl: '/config/maintenance#remote-backup',
            actionLabel: 'Noter la phrase de passe'
        );
    }

    /**
     * Re-armed, not inconclusive — see the class docblock for why both
     * cases have to clear a triggered alert rather than freeze it.
     */
    private function notMeasured(string $value): AlertReading
    {
        return new AlertReading(
            overTrigger: false,
            underRearm: true,
            value: $value,
            title: 'Aucune archive n\'est chiffrée hors site pour l\'instant.',
            why: 'Rien ne part de ce serveur, donc aucune phrase n\'ouvre quoi que ce soit ailleurs.',
            actionUrl: '/config/maintenance#remote-backup',
            actionLabel: 'Voir les sauvegardes'
        );
    }
}
